// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.2
// source: message_passing.proto

package main

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Problem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Latex       *string `protobuf:"bytes,1,req,name=latex" json:"latex,omitempty"`
	Description *string `protobuf:"bytes,2,req,name=description" json:"description,omitempty"`
	Title       *string `protobuf:"bytes,3,req,name=title" json:"title,omitempty"`
}

func (x *Problem) Reset() {
	*x = Problem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_passing_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Problem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Problem) ProtoMessage() {}

func (x *Problem) ProtoReflect() protoreflect.Message {
	mi := &file_message_passing_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Problem.ProtoReflect.Descriptor instead.
func (*Problem) Descriptor() ([]byte, []int) {
	return file_message_passing_proto_rawDescGZIP(), []int{0}
}

func (x *Problem) GetLatex() string {
	if x != nil && x.Latex != nil {
		return *x.Latex
	}
	return ""
}

func (x *Problem) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Problem) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

type ServerSent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Message:
	//
	//	*ServerSent_Remove
	//	*ServerSent_Add
	//	*ServerSent_Start
	//	*ServerSent_NewProblem_
	//	*ServerSent_End
	//	*ServerSent_ScoreUpdate_
	//	*ServerSent_Wrong
	Message isServerSent_Message `protobuf_oneof:"message"`
}

func (x *ServerSent) Reset() {
	*x = ServerSent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_passing_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerSent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerSent) ProtoMessage() {}

func (x *ServerSent) ProtoReflect() protoreflect.Message {
	mi := &file_message_passing_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerSent.ProtoReflect.Descriptor instead.
func (*ServerSent) Descriptor() ([]byte, []int) {
	return file_message_passing_proto_rawDescGZIP(), []int{1}
}

func (m *ServerSent) GetMessage() isServerSent_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (x *ServerSent) GetRemove() *ServerSent_RemoveMember {
	if x, ok := x.GetMessage().(*ServerSent_Remove); ok {
		return x.Remove
	}
	return nil
}

func (x *ServerSent) GetAdd() *ServerSent_AddMember {
	if x, ok := x.GetMessage().(*ServerSent_Add); ok {
		return x.Add
	}
	return nil
}

func (x *ServerSent) GetStart() *ServerSent_StartGame {
	if x, ok := x.GetMessage().(*ServerSent_Start); ok {
		return x.Start
	}
	return nil
}

func (x *ServerSent) GetNewProblem() *ServerSent_NewProblem {
	if x, ok := x.GetMessage().(*ServerSent_NewProblem_); ok {
		return x.NewProblem
	}
	return nil
}

func (x *ServerSent) GetEnd() *ServerSent_EndGame {
	if x, ok := x.GetMessage().(*ServerSent_End); ok {
		return x.End
	}
	return nil
}

func (x *ServerSent) GetScoreUpdate() *ServerSent_ScoreUpdate {
	if x, ok := x.GetMessage().(*ServerSent_ScoreUpdate_); ok {
		return x.ScoreUpdate
	}
	return nil
}

func (x *ServerSent) GetWrong() *ServerSent_WrongAnswer {
	if x, ok := x.GetMessage().(*ServerSent_Wrong); ok {
		return x.Wrong
	}
	return nil
}

type isServerSent_Message interface {
	isServerSent_Message()
}

type ServerSent_Remove struct {
	Remove *ServerSent_RemoveMember `protobuf:"bytes,1,opt,name=remove,oneof"`
}

type ServerSent_Add struct {
	Add *ServerSent_AddMember `protobuf:"bytes,2,opt,name=add,oneof"`
}

type ServerSent_Start struct {
	Start *ServerSent_StartGame `protobuf:"bytes,3,opt,name=start,oneof"`
}

type ServerSent_NewProblem_ struct {
	NewProblem *ServerSent_NewProblem `protobuf:"bytes,4,opt,name=new_problem,json=newProblem,oneof"`
}

type ServerSent_End struct {
	End *ServerSent_EndGame `protobuf:"bytes,5,opt,name=end,oneof"`
}

type ServerSent_ScoreUpdate_ struct {
	ScoreUpdate *ServerSent_ScoreUpdate `protobuf:"bytes,6,opt,name=score_update,json=scoreUpdate,oneof"`
}

type ServerSent_Wrong struct {
	Wrong *ServerSent_WrongAnswer `protobuf:"bytes,7,opt,name=wrong,oneof"`
}

func (*ServerSent_Remove) isServerSent_Message() {}

func (*ServerSent_Add) isServerSent_Message() {}

func (*ServerSent_Start) isServerSent_Message() {}

func (*ServerSent_NewProblem_) isServerSent_Message() {}

func (*ServerSent_End) isServerSent_Message() {}

func (*ServerSent_ScoreUpdate_) isServerSent_Message() {}

func (*ServerSent_Wrong) isServerSent_Message() {}

type ClientSent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Message:
	//
	//	*ClientSent_RequestStart_
	//	*ClientSent_Answer
	//	*ClientSent_RequestProblem_
	Message isClientSent_Message `protobuf_oneof:"message"`
}

func (x *ClientSent) Reset() {
	*x = ClientSent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_passing_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientSent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientSent) ProtoMessage() {}

func (x *ClientSent) ProtoReflect() protoreflect.Message {
	mi := &file_message_passing_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientSent.ProtoReflect.Descriptor instead.
func (*ClientSent) Descriptor() ([]byte, []int) {
	return file_message_passing_proto_rawDescGZIP(), []int{2}
}

func (m *ClientSent) GetMessage() isClientSent_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (x *ClientSent) GetRequestStart() *ClientSent_RequestStart {
	if x, ok := x.GetMessage().(*ClientSent_RequestStart_); ok {
		return x.RequestStart
	}
	return nil
}

func (x *ClientSent) GetAnswer() *ClientSent_GiveAnswer {
	if x, ok := x.GetMessage().(*ClientSent_Answer); ok {
		return x.Answer
	}
	return nil
}

func (x *ClientSent) GetRequestProblem() *ClientSent_RequestProblem {
	if x, ok := x.GetMessage().(*ClientSent_RequestProblem_); ok {
		return x.RequestProblem
	}
	return nil
}

type isClientSent_Message interface {
	isClientSent_Message()
}

type ClientSent_RequestStart_ struct {
	RequestStart *ClientSent_RequestStart `protobuf:"bytes,1,opt,name=request_start,json=requestStart,oneof"`
}

type ClientSent_Answer struct {
	Answer *ClientSent_GiveAnswer `protobuf:"bytes,2,opt,name=answer,oneof"`
}

type ClientSent_RequestProblem_ struct {
	RequestProblem *ClientSent_RequestProblem `protobuf:"bytes,3,opt,name=request_problem,json=requestProblem,oneof"`
}

func (*ClientSent_RequestStart_) isClientSent_Message() {}

func (*ClientSent_Answer) isClientSent_Message() {}

func (*ClientSent_RequestProblem_) isClientSent_Message() {}

type CreateLobbyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LobbyName *string `protobuf:"bytes,1,req,name=lobby_name,json=lobbyName" json:"lobby_name,omitempty"`
}

func (x *CreateLobbyReq) Reset() {
	*x = CreateLobbyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_passing_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateLobbyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLobbyReq) ProtoMessage() {}

func (x *CreateLobbyReq) ProtoReflect() protoreflect.Message {
	mi := &file_message_passing_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLobbyReq.ProtoReflect.Descriptor instead.
func (*CreateLobbyReq) Descriptor() ([]byte, []int) {
	return file_message_passing_proto_rawDescGZIP(), []int{3}
}

func (x *CreateLobbyReq) GetLobbyName() string {
	if x != nil && x.LobbyName != nil {
		return *x.LobbyName
	}
	return ""
}

type CreateLobbyRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LobbyId *string `protobuf:"bytes,1,req,name=lobby_id,json=lobbyId" json:"lobby_id,omitempty"`
}

func (x *CreateLobbyRes) Reset() {
	*x = CreateLobbyRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_passing_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateLobbyRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLobbyRes) ProtoMessage() {}

func (x *CreateLobbyRes) ProtoReflect() protoreflect.Message {
	mi := &file_message_passing_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLobbyRes.ProtoReflect.Descriptor instead.
func (*CreateLobbyRes) Descriptor() ([]byte, []int) {
	return file_message_passing_proto_rawDescGZIP(), []int{4}
}

func (x *CreateLobbyRes) GetLobbyId() string {
	if x != nil && x.LobbyId != nil {
		return *x.LobbyId
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username *string `protobuf:"bytes,1,req,name=username" json:"username,omitempty"`
	Password *string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	LobbyId  *string `protobuf:"bytes,3,req,name=lobby_id,json=lobbyId" json:"lobby_id,omitempty"`
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_passing_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_passing_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_message_passing_proto_rawDescGZIP(), []int{5}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

func (x *LoginRequest) GetLobbyId() string {
	if x != nil && x.LobbyId != nil {
		return *x.LobbyId
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Otp     *string `protobuf:"bytes,1,req,name=otp" json:"otp,omitempty"`
	IsOwner *bool   `protobuf:"varint,2,req,name=is_owner,json=isOwner" json:"is_owner,omitempty"`
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_passing_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_passing_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_message_passing_proto_rawDescGZIP(), []int{6}
}

func (x *LoginResponse) GetOtp() string {
	if x != nil && x.Otp != nil {
		return *x.Otp
	}
	return ""
}

func (x *LoginResponse) GetIsOwner() bool {
	if x != nil && x.IsOwner != nil {
		return *x.IsOwner
	}
	return false
}

type ServerSent_RemoveMember struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
}

func (x *ServerSent_RemoveMember) Reset() {
	*x = ServerSent_RemoveMember{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_passing_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerSent_RemoveMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerSent_RemoveMember) ProtoMessage() {}

func (x *ServerSent_RemoveMember) ProtoReflect() protoreflect.Message {
	mi := &file_message_passing_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerSent_RemoveMember.ProtoReflect.Descriptor instead.
func (*ServerSent_RemoveMember) Descriptor() ([]byte, []int) {
	return file_message_passing_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ServerSent_RemoveMember) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

type ServerSent_AddMember struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
}

func (x *ServerSent_AddMember) Reset() {
	*x = ServerSent_AddMember{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_passing_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerSent_AddMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerSent_AddMember) ProtoMessage() {}

func (x *ServerSent_AddMember) ProtoReflect() protoreflect.Message {
	mi := &file_message_passing_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerSent_AddMember.ProtoReflect.Descriptor instead.
func (*ServerSent_AddMember) Descriptor() ([]byte, []int) {
	return file_message_passing_proto_rawDescGZIP(), []int{1, 1}
}

func (x *ServerSent_AddMember) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

type ServerSent_StartGame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StartTime *timestamppb.Timestamp `protobuf:"bytes,1,req,name=startTime" json:"startTime,omitempty"`
	Duration  *timestamppb.Timestamp `protobuf:"bytes,2,req,name=duration" json:"duration,omitempty"`
}

func (x *ServerSent_StartGame) Reset() {
	*x = ServerSent_StartGame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_passing_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerSent_StartGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerSent_StartGame) ProtoMessage() {}

func (x *ServerSent_StartGame) ProtoReflect() protoreflect.Message {
	mi := &file_message_passing_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerSent_StartGame.ProtoReflect.Descriptor instead.
func (*ServerSent_StartGame) Descriptor() ([]byte, []int) {
	return file_message_passing_proto_rawDescGZIP(), []int{1, 2}
}

func (x *ServerSent_StartGame) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *ServerSent_StartGame) GetDuration() *timestamppb.Timestamp {
	if x != nil {
		return x.Duration
	}
	return nil
}

type ServerSent_EndGame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ServerSent_EndGame) Reset() {
	*x = ServerSent_EndGame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_passing_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerSent_EndGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerSent_EndGame) ProtoMessage() {}

func (x *ServerSent_EndGame) ProtoReflect() protoreflect.Message {
	mi := &file_message_passing_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerSent_EndGame.ProtoReflect.Descriptor instead.
func (*ServerSent_EndGame) Descriptor() ([]byte, []int) {
	return file_message_passing_proto_rawDescGZIP(), []int{1, 3}
}

type ServerSent_NewProblem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Problem *Problem `protobuf:"bytes,1,req,name=problem" json:"problem,omitempty"`
}

func (x *ServerSent_NewProblem) Reset() {
	*x = ServerSent_NewProblem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_passing_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerSent_NewProblem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerSent_NewProblem) ProtoMessage() {}

func (x *ServerSent_NewProblem) ProtoReflect() protoreflect.Message {
	mi := &file_message_passing_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerSent_NewProblem.ProtoReflect.Descriptor instead.
func (*ServerSent_NewProblem) Descriptor() ([]byte, []int) {
	return file_message_passing_proto_rawDescGZIP(), []int{1, 4}
}

func (x *ServerSent_NewProblem) GetProblem() *Problem {
	if x != nil {
		return x.Problem
	}
	return nil
}

type ServerSent_ScoreUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Score *int32  `protobuf:"varint,2,req,name=score" json:"score,omitempty"`
}

func (x *ServerSent_ScoreUpdate) Reset() {
	*x = ServerSent_ScoreUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_passing_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerSent_ScoreUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerSent_ScoreUpdate) ProtoMessage() {}

func (x *ServerSent_ScoreUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_message_passing_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerSent_ScoreUpdate.ProtoReflect.Descriptor instead.
func (*ServerSent_ScoreUpdate) Descriptor() ([]byte, []int) {
	return file_message_passing_proto_rawDescGZIP(), []int{1, 5}
}

func (x *ServerSent_ScoreUpdate) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *ServerSent_ScoreUpdate) GetScore() int32 {
	if x != nil && x.Score != nil {
		return *x.Score
	}
	return 0
}

type ServerSent_WrongAnswer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ServerSent_WrongAnswer) Reset() {
	*x = ServerSent_WrongAnswer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_passing_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerSent_WrongAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerSent_WrongAnswer) ProtoMessage() {}

func (x *ServerSent_WrongAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_message_passing_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerSent_WrongAnswer.ProtoReflect.Descriptor instead.
func (*ServerSent_WrongAnswer) Descriptor() ([]byte, []int) {
	return file_message_passing_proto_rawDescGZIP(), []int{1, 6}
}

type ClientSent_RequestStart struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Duration *timestamppb.Timestamp `protobuf:"bytes,1,req,name=duration" json:"duration,omitempty"`
	IsRandom *bool                  `protobuf:"varint,2,req,name=is_random,json=isRandom" json:"is_random,omitempty"`
	Problems []*Problem             `protobuf:"bytes,3,rep,name=problems" json:"problems,omitempty"`
}

func (x *ClientSent_RequestStart) Reset() {
	*x = ClientSent_RequestStart{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_passing_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientSent_RequestStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientSent_RequestStart) ProtoMessage() {}

func (x *ClientSent_RequestStart) ProtoReflect() protoreflect.Message {
	mi := &file_message_passing_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientSent_RequestStart.ProtoReflect.Descriptor instead.
func (*ClientSent_RequestStart) Descriptor() ([]byte, []int) {
	return file_message_passing_proto_rawDescGZIP(), []int{2, 0}
}

func (x *ClientSent_RequestStart) GetDuration() *timestamppb.Timestamp {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *ClientSent_RequestStart) GetIsRandom() bool {
	if x != nil && x.IsRandom != nil {
		return *x.IsRandom
	}
	return false
}

func (x *ClientSent_RequestStart) GetProblems() []*Problem {
	if x != nil {
		return x.Problems
	}
	return nil
}

type ClientSent_GiveAnswer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Answer *string `protobuf:"bytes,1,req,name=answer" json:"answer,omitempty"`
}

func (x *ClientSent_GiveAnswer) Reset() {
	*x = ClientSent_GiveAnswer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_passing_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientSent_GiveAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientSent_GiveAnswer) ProtoMessage() {}

func (x *ClientSent_GiveAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_message_passing_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientSent_GiveAnswer.ProtoReflect.Descriptor instead.
func (*ClientSent_GiveAnswer) Descriptor() ([]byte, []int) {
	return file_message_passing_proto_rawDescGZIP(), []int{2, 1}
}

func (x *ClientSent_GiveAnswer) GetAnswer() string {
	if x != nil && x.Answer != nil {
		return *x.Answer
	}
	return ""
}

type ClientSent_RequestProblem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ClientSent_RequestProblem) Reset() {
	*x = ClientSent_RequestProblem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_passing_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientSent_RequestProblem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientSent_RequestProblem) ProtoMessage() {}

func (x *ClientSent_RequestProblem) ProtoReflect() protoreflect.Message {
	mi := &file_message_passing_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientSent_RequestProblem.ProtoReflect.Descriptor instead.
func (*ClientSent_RequestProblem) Descriptor() ([]byte, []int) {
	return file_message_passing_proto_rawDescGZIP(), []int{2, 2}
}

var File_message_passing_proto protoreflect.FileDescriptor

var file_message_passing_proto_rawDesc = []byte{
	0x0a, 0x15, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x70, 0x61, 0x73, 0x73, 0x69, 0x6e,
	0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x57, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x62,
	0x6c, 0x65, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x74, 0x65, 0x78, 0x18, 0x01, 0x20, 0x02,
	0x28, 0x09, 0x52, 0x05, 0x6c, 0x61, 0x74, 0x65, 0x78, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x02, 0x28, 0x09, 0x52, 0x0b,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x02, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x22, 0xc1, 0x05, 0x0a, 0x0a, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x65, 0x6e, 0x74,
	0x12, 0x32, 0x0a, 0x06, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x18, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x48, 0x00, 0x52, 0x06, 0x72, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x12, 0x29, 0x0a, 0x03, 0x61, 0x64, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x65, 0x6e, 0x74, 0x2e, 0x41,
	0x64, 0x64, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x48, 0x00, 0x52, 0x03, 0x61, 0x64, 0x64, 0x12,
	0x2d, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15,
	0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x65, 0x6e, 0x74, 0x2e, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x47, 0x61, 0x6d, 0x65, 0x48, 0x00, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x39,
	0x0a, 0x0b, 0x6e, 0x65, 0x77, 0x5f, 0x70, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x65, 0x6e, 0x74,
	0x2e, 0x4e, 0x65, 0x77, 0x50, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x48, 0x00, 0x52, 0x0a, 0x6e,
	0x65, 0x77, 0x50, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x12, 0x27, 0x0a, 0x03, 0x65, 0x6e, 0x64,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53,
	0x65, 0x6e, 0x74, 0x2e, 0x45, 0x6e, 0x64, 0x47, 0x61, 0x6d, 0x65, 0x48, 0x00, 0x52, 0x03, 0x65,
	0x6e, 0x64, 0x12, 0x3c, 0x0a, 0x0c, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x5f, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x53, 0x65, 0x6e, 0x74, 0x2e, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x48, 0x00, 0x52, 0x0b, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x12, 0x2f, 0x0a, 0x05, 0x77, 0x72, 0x6f, 0x6e, 0x67, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x17, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x65, 0x6e, 0x74, 0x2e, 0x57, 0x72, 0x6f,
	0x6e, 0x67, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x48, 0x00, 0x52, 0x05, 0x77, 0x72, 0x6f, 0x6e,
	0x67, 0x1a, 0x22, 0x0a, 0x0c, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x1a, 0x1f, 0x0a, 0x09, 0x41, 0x64, 0x64, 0x4d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x1a, 0x7d, 0x0a, 0x09, 0x53, 0x74, 0x61, 0x72, 0x74, 0x47,
	0x61, 0x6d, 0x65, 0x12, 0x38, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x36, 0x0a,
	0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x08, 0x64, 0x75, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x09, 0x0a, 0x07, 0x45, 0x6e, 0x64, 0x47, 0x61, 0x6d, 0x65,
	0x1a, 0x30, 0x0a, 0x0a, 0x4e, 0x65, 0x77, 0x50, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x12, 0x22,
	0x0a, 0x07, 0x70, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32,
	0x08, 0x2e, 0x50, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x62, 0x6c,
	0x65, 0x6d, 0x1a, 0x37, 0x0a, 0x0b, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x02,
	0x20, 0x02, 0x28, 0x05, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x1a, 0x0d, 0x0a, 0x0b, 0x57,
	0x72, 0x6f, 0x6e, 0x67, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x42, 0x09, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x95, 0x03, 0x0a, 0x0a, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x53, 0x65, 0x6e, 0x74, 0x12, 0x3f, 0x0a, 0x0d, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x48, 0x00, 0x52, 0x0c, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x30, 0x0a, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x65,
	0x6e, 0x74, 0x2e, 0x47, 0x69, 0x76, 0x65, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x48, 0x00, 0x52,
	0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x12, 0x45, 0x0a, 0x0f, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x48, 0x00, 0x52, 0x0e,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x1a, 0x89,
	0x01, 0x0a, 0x0c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12,
	0x36, 0x0a, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x02, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x08, 0x64,
	0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x72, 0x61,
	0x6e, 0x64, 0x6f, 0x6d, 0x18, 0x02, 0x20, 0x02, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x52, 0x61,
	0x6e, 0x64, 0x6f, 0x6d, 0x12, 0x24, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x50, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d,
	0x52, 0x08, 0x70, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x73, 0x1a, 0x24, 0x0a, 0x0a, 0x47, 0x69,
	0x76, 0x65, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6e, 0x73, 0x77,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72,
	0x1a, 0x10, 0x0a, 0x0e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x62, 0x6c,
	0x65, 0x6d, 0x42, 0x09, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x2f, 0x0a,
	0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x52, 0x65, 0x71, 0x12,
	0x1d, 0x0a, 0x0a, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x02, 0x28, 0x09, 0x52, 0x09, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x2b,
	0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x52, 0x65, 0x73,
	0x12, 0x19, 0x0a, 0x08, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x02,
	0x28, 0x09, 0x52, 0x07, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x49, 0x64, 0x22, 0x61, 0x0a, 0x0c, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x5f, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x02, 0x28, 0x09, 0x52, 0x07, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x49, 0x64, 0x22, 0x3c,
	0x0a, 0x0d, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x6f, 0x74, 0x70, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x03, 0x6f, 0x74,
	0x70, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x73, 0x5f, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x02, 0x20,
	0x02, 0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x42, 0x07, 0x5a, 0x05,
	0x6d, 0x61, 0x69, 0x6e, 0x2f,
}

var (
	file_message_passing_proto_rawDescOnce sync.Once
	file_message_passing_proto_rawDescData = file_message_passing_proto_rawDesc
)

func file_message_passing_proto_rawDescGZIP() []byte {
	file_message_passing_proto_rawDescOnce.Do(func() {
		file_message_passing_proto_rawDescData = protoimpl.X.CompressGZIP(file_message_passing_proto_rawDescData)
	})
	return file_message_passing_proto_rawDescData
}

var file_message_passing_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_message_passing_proto_goTypes = []interface{}{
	(*Problem)(nil),                   // 0: Problem
	(*ServerSent)(nil),                // 1: ServerSent
	(*ClientSent)(nil),                // 2: ClientSent
	(*CreateLobbyReq)(nil),            // 3: CreateLobbyReq
	(*CreateLobbyRes)(nil),            // 4: CreateLobbyRes
	(*LoginRequest)(nil),              // 5: LoginRequest
	(*LoginResponse)(nil),             // 6: LoginResponse
	(*ServerSent_RemoveMember)(nil),   // 7: ServerSent.RemoveMember
	(*ServerSent_AddMember)(nil),      // 8: ServerSent.AddMember
	(*ServerSent_StartGame)(nil),      // 9: ServerSent.StartGame
	(*ServerSent_EndGame)(nil),        // 10: ServerSent.EndGame
	(*ServerSent_NewProblem)(nil),     // 11: ServerSent.NewProblem
	(*ServerSent_ScoreUpdate)(nil),    // 12: ServerSent.ScoreUpdate
	(*ServerSent_WrongAnswer)(nil),    // 13: ServerSent.WrongAnswer
	(*ClientSent_RequestStart)(nil),   // 14: ClientSent.RequestStart
	(*ClientSent_GiveAnswer)(nil),     // 15: ClientSent.GiveAnswer
	(*ClientSent_RequestProblem)(nil), // 16: ClientSent.RequestProblem
	(*timestamppb.Timestamp)(nil),     // 17: google.protobuf.Timestamp
}
var file_message_passing_proto_depIdxs = []int32{
	7,  // 0: ServerSent.remove:type_name -> ServerSent.RemoveMember
	8,  // 1: ServerSent.add:type_name -> ServerSent.AddMember
	9,  // 2: ServerSent.start:type_name -> ServerSent.StartGame
	11, // 3: ServerSent.new_problem:type_name -> ServerSent.NewProblem
	10, // 4: ServerSent.end:type_name -> ServerSent.EndGame
	12, // 5: ServerSent.score_update:type_name -> ServerSent.ScoreUpdate
	13, // 6: ServerSent.wrong:type_name -> ServerSent.WrongAnswer
	14, // 7: ClientSent.request_start:type_name -> ClientSent.RequestStart
	15, // 8: ClientSent.answer:type_name -> ClientSent.GiveAnswer
	16, // 9: ClientSent.request_problem:type_name -> ClientSent.RequestProblem
	17, // 10: ServerSent.StartGame.startTime:type_name -> google.protobuf.Timestamp
	17, // 11: ServerSent.StartGame.duration:type_name -> google.protobuf.Timestamp
	0,  // 12: ServerSent.NewProblem.problem:type_name -> Problem
	17, // 13: ClientSent.RequestStart.duration:type_name -> google.protobuf.Timestamp
	0,  // 14: ClientSent.RequestStart.problems:type_name -> Problem
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_message_passing_proto_init() }
func file_message_passing_proto_init() {
	if File_message_passing_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_message_passing_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Problem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_passing_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerSent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_passing_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientSent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_passing_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateLobbyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_passing_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateLobbyRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_passing_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_passing_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_passing_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerSent_RemoveMember); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_passing_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerSent_AddMember); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_passing_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerSent_StartGame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_passing_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerSent_EndGame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_passing_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerSent_NewProblem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_passing_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerSent_ScoreUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_passing_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerSent_WrongAnswer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_passing_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientSent_RequestStart); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_passing_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientSent_GiveAnswer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_passing_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientSent_RequestProblem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_message_passing_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*ServerSent_Remove)(nil),
		(*ServerSent_Add)(nil),
		(*ServerSent_Start)(nil),
		(*ServerSent_NewProblem_)(nil),
		(*ServerSent_End)(nil),
		(*ServerSent_ScoreUpdate_)(nil),
		(*ServerSent_Wrong)(nil),
	}
	file_message_passing_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*ClientSent_RequestStart_)(nil),
		(*ClientSent_Answer)(nil),
		(*ClientSent_RequestProblem_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_message_passing_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_passing_proto_goTypes,
		DependencyIndexes: file_message_passing_proto_depIdxs,
		MessageInfos:      file_message_passing_proto_msgTypes,
	}.Build()
	File_message_passing_proto = out.File
	file_message_passing_proto_rawDesc = nil
	file_message_passing_proto_goTypes = nil
	file_message_passing_proto_depIdxs = nil
}
